<a href="https://colab.research.google.com/github/rrsrnc/DataScience/blob/main/week9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

scores  mean

In [51]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


In [98]:
data= np.genfromtxt("cric_data.tsv",delimiter="\t",skip_header=1,usecols=(1,2,3))
sachin=data[:,0]
rahul=data[:,1]
india=data[:,2]
np.mean(data,axis=0)
np.median(data,axis=0)


array([ 27.,  22., 216.])

In [91]:
def stats(col):
  mean=np.mean(col)
  median=np.median(col)
  percentiles=np.percentile(col,[25,75])
  iqr=percentiles[1]-percentiles[0]
  print("mean:",mean)
  print("median:",median)
  print("iqr:",iqr)

In [93]:
stats(sachin)

mean: 39.87555555555556
median: 27.0
iqr: 57.0


In [94]:
stats(rahul)

mean: 32.062222222222225
median: 22.0
iqr: 46.0


In [95]:
stats(india)

mean: 220.79555555555555
median: 216.0
iqr: 98.0


sachin histogram

In [53]:
np.histogram(sachin,bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

sachin score mean with group of 25 macthes


In [101]:
sachinMeanGrp=np.mean(sachin.reshape(9,25),axis=1)
print(sachinMeanGrp)

[33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


sachin score mean where he scored a century

In [102]:
sachinCenturyScore=sachin[sachin>=100]
meanSachinCenturyScore=np.mean(sachinCenturyScore)
print(meanSachinCenturyScore)

125.0


sachin mean score when rahul scored less than 10

In [104]:
sachinOverrahul=sachin[rahul<=10]
meanSachinOverRahul=np.mean(sachinOverrahul)
print(meanSachinOverRahul)

40.2112676056338


In [109]:
indiaQuartiles=np.percentile(india,[25,50,75,100])
print(indiaQuartiles)

[175. 216. 273. 499.]


In [121]:
sachine1Q=np.mean(sachin[india<indiaQuartiles[0]])
# sachine2Q=np.mean(sachin[(india>indiaQuartiles[0]) & (india<=indiaQuartiles[1])])
# sachine3Q=np.mean(sachin[(india>indiaQuartiles[2]) & (india<=indiaQuartiles[3])])
sachine2Q=np.mean(sachin[(india<indiaQuartiles[1])])
sachine3Q=np.mean(sachin[(india<indiaQuartiles[2])])
sachine4Q=np.mean(sachin[(india<indiaQuartiles[3])])
print(sachine1Q)
print(sachine2Q)
print(sachine3Q)
print(sachine4Q)


19.672727272727272
28.18018018018018
31.688622754491018
39.799107142857146


In [142]:
indices=india<indiaQuartiles.reshape(4,1)
for i in range(4):
  print(np.mean(sachin[indices[i,:]]))


19.672727272727272
28.18018018018018
31.688622754491018
39.799107142857146


In [ ]:
snr=data[:,0:2]
higherIndices=np.argmax(snr,axis=1)
np.where(higherIndices==0,"sachin","rahul")

matches taken to score 1000 and so on

In [152]:
sc=np.cumsum(sachin)
np.histogram(sc,bins=np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))